### ISSUE TITLE
example_data explanations

### ISSUE THREAD

**Issue by maxemil** [ssolo/ALE#7]
Hej,

I just have a few questions about the example_data and the associated README and output files.

1. in the documentation, you say we discard the first 1000 trees as burnin, but actually the 2 files .treelist only contain 9504 trees, and thus no burnin is discarded at all. Is that supposed to be the case? could it be that you already discarded the burnin during the sampling process?

2. I understand that in the ouput file .uml_rec i find a number of reconsiled trees and in .ucons_tree the consensus ml tree, but why is it that the consensus tree is not annotated with any events, is there a way to get the events on that tree or am i missing something in how to interpret these two files?

hope that you can give me some hints, as I would really like to use ALE for my work!
cheers,
Max

**Comment by ssolo** [comment]
Re.1.

The example comes from here: http://datadryad.org/resource/doi:10.5061/dryad.pv6df

For the majority of the alignments  I ran two phylobayes chains, each sampling 5500 trees. To construct the .ale-s I used both chains discarding the first 500 from each. Due to details of how the queue was managed on the cluster I ran this on, in particular limits on runtime and hard disk space, some families had fewer samples.

Re.2.

The consensus tree you can find in the .uml_rec file is the unrooted majority consensus of the sampled reconciled gene trees, i.e. it is derived such that rooting and the reconciliation is ignored and only the unrooted  gene tree topology is considered. While it would certainly be interesting, I am not aware of any method  that could produce a consensus of reconciled gene trees. 

There are two reasons why we do not provide a reconciliation of the  majority consensus that you can find in the .uml_rec file:

1. From a theoretical point of view it is not clear what this would mean.

2. From a technical point of view, the unrooted majority consensus is not guaranteed to be bifurcating, and multifurcating trees cannot be handled by ALE.   

However, if you wish to obtain a reconciled version of the consensus you can do the following:

1. check if the consensus tree you can find in the .uml_rec file is bifurcating;
2. if it is, then you can use ALEobserve to construct a .ale from this single tree and then run e.g. ALEml.

**Comment by maxemil** [comment]
Hej,
Thanks for the answers!

To 2:
Certainly you mean that the majority consensus tree is in the .ucons_tree file, not in the .uml_rec file? Apart from that, I understand the reasons for not providing a reconciled consensus. But i don't really see the application of the consensus in this case then. I would now be interested in the DTL rates only
